version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Next.js app service
  nextjs:
    build: .
    container_name: nextjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/survey-app

volumes:
  mongodb_data: